/* V.34 data mode: framing, shell mapping, the encoder of Figure 4 and a
 * decoder for it. See v34_codec.h. */
#include "v34_codec.h"

#include <math.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>

/* ---------------------------------------------------------------- tables */

const int V34_SR_A[V34_NUM_SR] = { 1, 8, 7, 5, 4, 10 };
const int V34_SR_C[V34_NUM_SR] = { 1, 7, 6, 4, 3, 7 };
const int V34_CAR_D[V34_NUM_SR][2] = { { 2, 3 }, { 3, 2 }, { 3, 2 }, { 3, 2 }, { 4, 3 }, { 4, 4 } };
const int V34_CAR_E[V34_NUM_SR][2] = { { 3, 4 }, { 5, 3 }, { 5, 3 }, { 5, 3 }, { 7, 5 }, { 7, 7 } };
const int V34_SR_MAX_RATE[V34_NUM_SR] = { 21600, 26400, 26400, 28800, 31200, 33600 };
const char *const V34_SR_NAME[V34_NUM_SR] = { "2400", "2743", "2800", "3000", "3200", "3429" };

/* Table 7, and the auxiliary channel's W from 8.3. */
static const int SR_J[V34_NUM_SR] = { 7, 8, 7, 7, 7, 8 };
static const int SR_P[V34_NUM_SR] = { 12, 12, 14, 15, 16, 15 };
static const int SR_W[V34_NUM_SR] = { 8, 7, 8, 8, 8, 7 };

double v34_symbol_rate(int sr)
{
    return 2400.0 * V34_SR_A[sr] / V34_SR_C[sr];
}

double v34_carrier(int sr, bool high)
{
    return v34_symbol_rate(sr) * V34_CAR_D[sr][high] / V34_CAR_E[sr][high];
}

int8_t v34_super[V34_QUARTER][2];

/* Figure 5. The quarter superconstellation is every point of the odd grid
 * with both coordinates 1 modulo 4, labelled in order of increasing
 * magnitude and, between points of equal magnitude, decreasing imaginary
 * part. Generated rather than transcribed, and checked against the figure
 * by the unit tests. */
static void build_super(void)
{
    int n = 0;
    int cand[2][2048];

    for (int y = -47; y <= 49; y += 4)
        for (int x = -47; x <= 49; x += 4)
        {
            cand[0][n] = x;
            cand[1][n] = y;
            n++;
        }
    for (int i = 0; i < V34_QUARTER; i++)
    {
        int best = -1;

        for (int k = 0; k < n; k++)
        {
            int e, be;

            if (cand[0][k] > 1000)
                continue;
            if (best < 0)
            {
                best = k;
                continue;
            }
            e = cand[0][k] * cand[0][k] + cand[1][k] * cand[1][k];
            be = cand[0][best] * cand[0][best] + cand[1][best] * cand[1][best];
            if (e < be || (e == be && cand[1][k] > cand[1][best]))
                best = k;
        }
        v34_super[i][0] = (int8_t) cand[0][best];
        v34_super[i][1] = (int8_t) cand[1][best];
        cand[0][best] = 10000;
    }
}

/* Figure 9. Writing a = (re + im)/2 and b = (re - im)/2, the label depends
 * only on a and b modulo 4 - the 8-way partition's sublattice is generated by
 * 4 + 4j and 4 - 4j - and its two low bits count the clockwise quarter turns
 * that take the point there from the quarter superconstellation, all of whose
 * points carry 000 or 100. */
int v34_subset_label(int re, int im)
{
    int xr = re ^ im;
    int x = xr & 2;

    return ((xr & 4) ^ (x << 1)) | (re & 2) | (x >> 1);
}

/* Table 13: [s(2m)][s(2m + 1)] -> Y4 Y3 Y2 Y1. */
static const uint8_t TABLE13[8][8] = {
    { 0x0, 0x0, 0x1, 0x1, 0x8, 0x8, 0x9, 0x9 },
    { 0x3, 0x2, 0x2, 0x3, 0xB, 0xA, 0xA, 0xB },
    { 0x5, 0x5, 0x4, 0x4, 0xD, 0xD, 0xC, 0xC },
    { 0x6, 0x7, 0x7, 0x6, 0xE, 0xF, 0xF, 0xE },
    { 0x8, 0x8, 0x9, 0x9, 0x0, 0x0, 0x1, 0x1 },
    { 0xB, 0xA, 0xA, 0xB, 0x3, 0x2, 0x2, 0x3 },
    { 0xD, 0xD, 0xC, 0xC, 0x5, 0x5, 0x4, 0x4 },
    { 0xE, 0xF, 0xF, 0xE, 0x6, 0x7, 0x7, 0x6 },
};

/* Figures 10 to 12 as next-state tables, [state][Y4 Y3 Y2 Y1]. Each state
 * packs the delay elements with the first one most significant, so its low
 * bit is the last one, whose output is Y0. */
static uint8_t conv16[16][16], conv32[32][16], conv64[64][16];

static void build_conv(void)
{
    for (int st = 0; st < 64; st++)
        for (int yy = 0; yy < 16; yy++)
        {
            int y1 = yy & 1, y2 = (yy >> 1) & 1, y3 = (yy >> 2) & 1, y4 = (yy >> 3) & 1;

            if (st < 16)
            {
                int d1 = (st >> 3) & 1, d2 = (st >> 2) & 1, d3 = (st >> 1) & 1, d4 = st & 1;
                int y0 = d4;
                int n1 = y0, n2 = d1 ^ y2 ^ y0, n3 = d2 ^ y2, n4 = d3 ^ y1;

                conv16[st][yy] = (uint8_t) ((n1 << 3) | (n2 << 2) | (n3 << 1) | n4);
            }
            if (st < 32)
            {
                int d1 = (st >> 4) & 1, d2 = (st >> 3) & 1, d3 = (st >> 2) & 1, d4 = (st >> 1) & 1, d5 = st & 1;
                int y0 = d5;
                int n1 = y0, n2 = d1 ^ y2, n3 = d2 ^ y1, n4 = d3 ^ y4, n5 = d4 ^ y2;

                conv32[st][yy] = (uint8_t) ((n1 << 4) | (n2 << 3) | (n3 << 2) | (n4 << 1) | n5);
            }
            {
                int d1 = (st >> 5) & 1, d2 = (st >> 4) & 1, d3 = (st >> 3) & 1, d4 = (st >> 2) & 1;
                int d5 = (st >> 1) & 1, d6 = st & 1;
                int n1 = y4 ^ d1 ^ d2 ^ (d3 & (d2 ^ y1));
                int n2 = d1 ^ d2 ^ d4 ^ y3 ^ (y2 & d3);
                int n3 = d2 ^ y1 ^ d3;
                int n4 = d3;
                int n5 = d6;
                int n6 = d5 ^ y2 ^ d3;

                conv64[st][yy] = (uint8_t) ((n1 << 5) | (n2 << 4) | (n3 << 3) | (n4 << 2) | (n5 << 1) | n6);
            }
        }
}

/* For the decoder: which (a mod 4, b mod 4) each label is, and a lookup from
 * a point back to its label in the quarter superconstellation. */
static int8_t label_ab[8][2];
#define IDX_SPAN 50
static int16_t quarter_index[2 * IDX_SPAN][2 * IDX_SPAN];

static void build_decoder_tables(void)
{
    for (int i = 0; i < 2 * IDX_SPAN; i++)
        for (int k = 0; k < 2 * IDX_SPAN; k++)
            quarter_index[i][k] = -1;
    for (int i = 0; i < V34_QUARTER; i++)
        quarter_index[v34_super[i][0] + IDX_SPAN][v34_super[i][1] + IDX_SPAN] = (int16_t) i;
    for (int a = 0; a < 4; a++)
        for (int b = 0; b < 4; b++)
            if ((a + b) & 1)
            {
                int s = v34_subset_label(a + b, a - b);

                label_ab[s][0] = (int8_t) a;
                label_ab[s][1] = (int8_t) b;
            }
}

static pthread_once_t tables_once = PTHREAD_ONCE_INIT;

static void build_tables(void)
{
    build_super();
    build_conv();
    build_decoder_tables();
}

static void tables(void)
{
    pthread_once(&tables_once, build_tables);
}

/* ---------------------------------------------------------- frame params */

bool v34_frame_params(const v34_data_params_t *p, v34_frame_t *f)
{
    int rtotal;
    double two_k8;

    tables();
    memset(f, 0, sizeof(*f));
    /* Table 8: 2400 bit/s only at 2400 symbols a second, 4800 the least at
     * the rest. */
    if (p->sr < 0 || p->sr >= V34_NUM_SR || p->rate < (p->sr == V34_S2400 ? 2400 : 4800) ||
        p->rate > V34_SR_MAX_RATE[p->sr] || p->rate % 2400 != 0)
        return false;
    f->J = SR_J[p->sr];
    f->P = SR_P[p->sr];
    f->W = p->aux ? SR_W[p->sr] : 0;
    rtotal = p->rate + (p->aux ? 200 : 0);
    /* (8-1): N = R 0.28 / J, which is always a whole number. */
    f->N = rtotal * 28 / (100 * f->J);
    f->b = (f->N + f->P - 1) / f->P;
    f->r = f->N - (f->b - 1) * f->P;
    /* (9-1) */
    if (f->b <= 12)
    {
        f->K = 0;
        f->q = 0;
    }
    else
    {
        f->q = 0;
        f->K = f->b - 12;
        while (f->K >= 32)
        {
            f->q++;
            f->K -= 8;
        }
    }
    /* 9.2: the smallest M with M^8 >= 2^K, and the nearest integer to 1.25
     * 2^(K/8), no less than that. */
    f->M = 1;
    while (pow((double) f->M, 8.0) < ldexp(1.0, f->K))
        f->M++;
    if (p->expanded)
    {
        int me;

        /* Halves round up: Table 10 has 3 for K = 8, where 1.25 2^(K/8) is 2.5. */
        two_k8 = pow(2.0, f->K / 8.0);
        me = (int) floor(1.25 * two_k8 + 0.5);

        if (me > f->M)
            f->M = me;
    }
    /* (9-2) */
    f->L = 4 * f->M << f->q;
    /* (9-29) */
    f->w = (f->b >= 56) ? 2 : 1;
    return f->L / 4 <= V34_QUARTER;
}

/* 8.2: high frames are where the counter, advanced by r every mapping frame,
 * reaches P. */
unsigned v34_swp(const v34_frame_t *f)
{
    unsigned pat = 0;
    int cnt = 0;

    for (int i = 0; i < f->P; i++)
    {
        cnt += f->r;
        pat <<= 1;
        if (cnt >= f->P)
        {
            pat |= 1;
            cnt -= f->P;
        }
    }
    return pat;
}

unsigned v34_amp(const v34_frame_t *f)
{
    unsigned pat = 0;
    int cnt = 0;

    for (int i = 0; i < f->P; i++)
    {
        cnt += f->W;
        pat <<= 1;
        if (cnt >= f->P)
        {
            pat |= 1;
            cnt -= f->P;
        }
    }
    return pat;
}

/* High or low, and whether I1(i,0) is auxiliary, for mapping frame i
 * counted from the start of B1: the counters restart with every data frame. */
static bool frame_is_high(const v34_frame_t *f, long long i)
{
    int pos = (int) (i % f->P);

    return ((pos + 1) * f->r) / f->P != (pos * f->r) / f->P;
}

static bool frame_has_aux(const v34_frame_t *f, long long i)
{
    int pos = (int) (i % f->P);

    return f->W > 0 && ((pos + 1) * f->W) / f->P != (pos * f->W) / f->P;
}

/* Table 12, left-most bit first: 01 11 01 11 11 11 10 10. B1 is sent as the
 * last data frame of a superframe, and the superframe proper starts after
 * it. */
int v34_v0(const v34_frame_t *f, long long m)
{
    long long half = 2LL * f->P;
    int idx;

    if (m % half != 0)
        return 0;
    idx = (int) ((m / half + 2 * f->J - 2) % (2 * f->J));
    return (0x5FEE >> idx) & 1;
}

int v34_scramble(uint32_t *reg, int tap, int in)
{
    int out = (in ^ (int) (*reg >> (tap - 1)) ^ (int) (*reg >> 22)) & 1;

    *reg = ((*reg << 1) | (uint32_t) out) & 0x7FFFFFu;
    return out;
}

int v34_descramble(uint32_t *reg, int tap, int in)
{
    int out = (in ^ (int) (*reg >> (tap - 1)) ^ (int) (*reg >> 22)) & 1;

    *reg = ((*reg << 1) | (uint32_t) (in & 1)) & 0x7FFFFFu;
    return out;
}

/* ------------------------------------------------------------ shell map */

void v34_shell_init(v34_shell_t *s, int M)
{
    memset(s, 0, sizeof(*s));
    s->M = M;
    /* (9-3) to (9-6) */
    for (int p = 0; p <= 2 * (M - 1); p++)
        s->g2[p] = (uint64_t) (M - abs(p - M + 1));
    for (int p = 0; p <= 4 * (M - 1); p++)
        for (int k = 0; k <= p; k++)
            s->g4[p] += s->g2[k] * s->g2[p - k];
    for (int p = 0; p <= 8 * (M - 1); p++)
        for (int k = 0; k <= p; k++)
            s->g8[p] += s->g4[k] * s->g4[p - k];
    for (int p = 1; p <= 8 * (M - 1) + 1; p++)
        s->z8[p] = s->z8[p - 1] + s->g8[p - 1];
}

static uint64_t g2_at(const v34_shell_t *s, int p)
{
    return (p >= 0 && p <= 2 * (s->M - 1)) ? s->g2[p] : 0;
}

static uint64_t g4_at(const v34_shell_t *s, int p)
{
    return (p >= 0 && p <= 4 * (s->M - 1)) ? s->g4[p] : 0;
}

/* 9.4, as written. */
void v34_shell_map(const v34_shell_t *s, uint32_t r0in, int m[8])
{
    const int M = s->M;
    uint64_t r0 = r0in, r1, r2, r3, r4, r5;
    int A = 0, B = 0, C = 0, D = 0;
    int E, F, G, H;

    if (M <= 1)
    {
        memset(m, 0, 8 * sizeof(int));
        return;
    }
    /* 2) */
    while (A + 1 <= 8 * (M - 1) && s->z8[A + 1] <= r0)
        A++;
    /* 3) */
    r1 = r0 - s->z8[A];
    for (;;)
    {
        uint64_t t = g4_at(s, B) * g4_at(s, A - B);

        if (B >= A || r1 < t)
            break;
        r1 -= t;
        B++;
    }
    /* 4) */
    r2 = r1 % s->g4[B];
    r3 = r1 / s->g4[B];
    /* 5.1) and 5.2) */
    r4 = r2;
    for (;;)
    {
        uint64_t t = g2_at(s, C) * g2_at(s, B - C);

        if (C >= B || r4 < t)
            break;
        r4 -= t;
        C++;
    }
    r5 = r3;
    for (;;)
    {
        uint64_t t = g2_at(s, D) * g2_at(s, A - B - D);

        if (D >= A - B || r5 < t)
            break;
        r5 -= t;
        D++;
    }
    /* 6.1) and 6.2) */
    E = (int) (r4 % s->g2[C]);
    F = (int) (r4 / s->g2[C]);
    G = (int) (r5 % s->g2[D]);
    H = (int) (r5 / s->g2[D]);
    /* (9-17) to (9-24) */
    if (C < M)
    {
        m[0] = E;
        m[1] = C - m[0];
    }
    else
    {
        m[1] = M - 1 - E;
        m[0] = C - m[1];
    }
    if (B - C < M)
    {
        m[2] = F;
        m[3] = B - C - m[2];
    }
    else
    {
        m[3] = M - 1 - F;
        m[2] = B - C - m[3];
    }
    if (D < M)
    {
        m[4] = G;
        m[5] = D - m[4];
    }
    else
    {
        m[5] = M - 1 - G;
        m[4] = D - m[5];
    }
    if (A - B - D < M)
    {
        m[6] = H;
        m[7] = A - B - D - m[6];
    }
    else
    {
        m[7] = M - 1 - H;
        m[6] = A - B - D - m[7];
    }
}

/* Running the algorithm backwards: each step of it chose the largest value
 * leaving a non-negative remainder, so the remainder is recovered by adding
 * back what each step took away. */
bool v34_shell_unmap(const v34_shell_t *s, const int m[8], int K, uint32_t *r0out)
{
    const int M = s->M;
    int A, B, C, D, E, F, G, H;
    uint64_t r0, r1, r2, r3, r4, r5;

    *r0out = 0;
    if (M <= 1)
        return m[0] == 0 && m[1] == 0 && m[2] == 0 && m[3] == 0 && m[4] == 0 && m[5] == 0 && m[6] == 0 &&
               m[7] == 0;
    for (int i = 0; i < 8; i++)
        if (m[i] < 0 || m[i] >= M)
            return false;
    C = m[0] + m[1];
    B = C + m[2] + m[3];
    D = m[4] + m[5];
    A = B + D + m[6] + m[7];
    E = (C < M) ? m[0] : M - 1 - m[1];
    F = (B - C < M) ? m[2] : M - 1 - m[3];
    G = (D < M) ? m[4] : M - 1 - m[5];
    H = (A - B - D < M) ? m[6] : M - 1 - m[7];
    r4 = (uint64_t) F * s->g2[C] + (uint64_t) E;
    r2 = r4;
    for (int p = 0; p < C; p++)
        r2 += g2_at(s, p) * g2_at(s, B - p);
    r5 = (uint64_t) H * s->g2[D] + (uint64_t) G;
    r3 = r5;
    for (int p = 0; p < D; p++)
        r3 += g2_at(s, p) * g2_at(s, A - B - p);
    r1 = r3 * s->g4[B] + r2;
    r0 = r1 + s->z8[A];
    for (int p = 0; p < B; p++)
        r0 += g4_at(s, p) * g4_at(s, A - p);
    if (K < 32 && r0 >= (1ULL << K))
        return false;
    *r0out = (uint32_t) r0;
    return true;
}

/* -------------------------------------------------------------- encoder */

static void rot_cw(int x, int y, int quads, int *ox, int *oy)
{
    switch (quads & 3)
    {
    case 0:
        *ox = x;
        *oy = y;
        break;
    case 1:
        *ox = y;
        *oy = -x;
        break;
    case 2:
        *ox = -x;
        *oy = -y;
        break;
    default:
        *ox = -y;
        *oy = x;
        break;
    }
}

void v34_enc_init(v34_enc_t *e, const v34_data_params_t *p, int scr_tap)
{
    tables();
    memset(e, 0, sizeof(*e));
    e->p = *p;
    v34_frame_params(p, &e->f);
    v34_shell_init(&e->shell, e->f.M);
    e->scr_tap = scr_tap;
    e->ex = 0.0;
}

void v34_enc_set_energy(v34_enc_t *e, double ex)
{
    e->ex = ex;
}

/* Rounds a value with sh fractional bits to the nearest whole one, ties going
 * to the smaller magnitude - the rule of 9.6.2 items 2) and 3). */
static int64_t round_toward_zero_ties(int64_t v, int sh)
{
    int64_t half = (int64_t) 1 << (sh - 1);

    if (v >= 0)
        return (v + half - 1) >> sh;
    return -((-v + half - 1) >> sh);
}

/* 9.6.2 items 1) to 3): p(n) and c(n) from x(n-1), x(n-2), x(n-3). x is held
 * with 7 fractional bits and h with 14, so the sum has 21, and is exact. */
static void precoder_step(v34_enc_t *e)
{
    int64_t sre = 0, sim = 0;

    for (int k = 0; k < 3; k++)
    {
        int64_t xr = e->xh[k][0], xi = e->xh[k][1];
        int64_t hr = e->p.h[k][0], hi = e->p.h[k][1];

        sre += xr * hr - xi * hi;
        sim += xr * hi + xi * hr;
    }
    e->pq[0] = (int32_t) round_toward_zero_ties(sre, 14);
    e->pq[1] = (int32_t) round_toward_zero_ties(sim, 14);
    /* c: the nearest multiple of 2^w, from p with 7 fractional bits. */
    for (int k = 0; k < 2; k++)
        e->c[k] = (int32_t) (round_toward_zero_ties(e->pq[k], 7 + e->f.w) << e->f.w);
}

static int next_bit(v34_enc_t *e, v34_get_bit_t get_bit, void *user)
{
    int bit = (get_bit != NULL && !e->b1) ? (get_bit(user) & 1) : 1;

    return v34_scramble(&e->scr, e->scr_tap, bit);
}

static int conv_next(const v34_enc_t *e, int state, int yy)
{
    switch (e->p.trellis)
    {
    case 32:
        return conv32[state][yy];
    case 64:
        return conv64[state][yy];
    default:
        return conv16[state][yy];
    }
}

/* One 2D symbol through the precoder (Table 11 steps 2-3 and 7-8). Returns
 * the subset label of y(n). */
static int precode(v34_enc_t *e, int ur, int ui, v34_cf_t *out)
{
    int yr = ur + e->c[0], yi = ui + e->c[1];
    int32_t xr = (yr << 7) - e->pq[0];
    int32_t xi = (yi << 7) - e->pq[1];
    double fr = xr / 128.0, fi = xi / 128.0;

    if (e->p.nonlinear && e->ex > 0.0)
    {
        /* (9-33) to (9-35) */
        double zeta = 0.3125 * (fr * fr + fi * fi) / e->ex;
        double phi = 1.0 + zeta / 6.0 + zeta * zeta / 120.0;

        fr *= phi;
        fi *= phi;
    }
    *out = (float) fr + I * (float) fi;
    e->xh[2][0] = e->xh[1][0];
    e->xh[2][1] = e->xh[1][1];
    e->xh[1][0] = e->xh[0][0];
    e->xh[1][1] = e->xh[0][1];
    e->xh[0][0] = xr;
    e->xh[0][1] = xi;
    precoder_step(e);
    return v34_subset_label(yr, yi);
}

void v34_enc_frame(v34_enc_t *e, v34_get_bit_t get_bit, void *user, v34_get_bit_t aux_bit, void *aux_user,
                   v34_cf_t out[8])
{
    const v34_frame_t *f = &e->f;
    bool high = frame_is_high(f, e->i);
    bool aux = frame_has_aux(f, e->i);
    uint32_t r0 = 0;
    int ib[4][3] = { { 0 } };
    int qb[8] = { 0 };
    int rings[8] = { 0 };
    int with_i3;

    /* 9.3: the first K bits (K - 1 and a zero, in a low frame) to the shell
     * mapper, then three I bits and two lots of q Q bits per 4D symbol. When
     * the auxiliary channel has this frame, its bit is I1(i,0), and is not
     * scrambled (clause 7). */
    if (f->K > 0)
    {
        int kk = high ? f->K : f->K - 1;

        for (int k = 0; k < kk; k++)
            r0 |= (uint32_t) next_bit(e, get_bit, user) << k;
        with_i3 = 4;
    }
    else
    {
        /* 9.3.2: 8, 9, 11 or 12 bits; the groups past the first b - 8 lack I3. */
        with_i3 = (high ? f->b : f->b - 1) - 8;
    }
    for (int j = 0; j < 4; j++)
    {
        if (j == 0 && aux)
            ib[0][0] = (aux_bit != NULL) ? (aux_bit(aux_user) & 1) : 0;
        else
            ib[j][0] = next_bit(e, get_bit, user);
        ib[j][1] = next_bit(e, get_bit, user);
        ib[j][2] = (j < with_i3) ? next_bit(e, get_bit, user) : 0;
        for (int k = 0; k < 2; k++)
            for (int t = 0; t < f->q; t++)
                qb[2 * j + k] |= next_bit(e, get_bit, user) << t;
    }
    if (f->K > 0)
        v34_shell_map(&e->shell, r0, rings);

    for (int j = 0; j < 4; j++)
    {
        long long m = 4 * e->i + j;
        int s0, s1, c0, u0, rot;
        int idx, ur, ui;
        int32_t c2m[2];

        /* 9.5 */
        e->z = (e->z + ib[j][1] + 2 * ib[j][2]) & 3;
        /* Step 1 to 3 */
        idx = qb[2 * j] + (rings[2 * j] << f->q);
        rot_cw(v34_super[idx][0], v34_super[idx][1], e->z, &ur, &ui);
        c2m[0] = e->c[0];
        c2m[1] = e->c[1];
        s0 = precode(e, ur, ui, &out[2 * j]);
        /* Steps 4 and 5: 9.6.3.3 and (9-32) */
        c0 = ((c2m[0] / 2 + c2m[1] / 2) ^ (e->c[0] / 2 + e->c[1] / 2)) & 1;
        u0 = e->y0 ^ c0 ^ v34_v0(f, m);
        /* Steps 6 to 8 */
        rot = e->z + 2 * ib[j][0] + u0;
        idx = qb[2 * j + 1] + (rings[2 * j + 1] << f->q);
        rot_cw(v34_super[idx][0], v34_super[idx][1], rot, &ur, &ui);
        s1 = precode(e, ur, ui, &out[2 * j + 1]);
        /* Step 9: Y0(m + 1) is what the encoder puts out once Y(m) is in. */
        e->state = conv_next(e, e->state, TABLE13[s0][s1]);
        e->y0 = e->state & 1;
    }
    e->i++;
}

static uint32_t prng_state;

static int prng_bit(void *user)
{
    (void) user;
    prng_state ^= prng_state << 13;
    prng_state ^= prng_state >> 17;
    prng_state ^= prng_state << 5;
    return (int) (prng_state >> 31);
}

void v34_data_energy(const v34_data_params_t *p, double *ex, double *exn)
{
    static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;
    v34_enc_t *e = malloc(sizeof(*e));
    v34_data_params_t q = *p;
    const int frames = 4000;
    double sum = 0.0;

    *ex = *exn = 0.0;
    if (e == NULL)
        return;
    pthread_mutex_lock(&lock);
    for (int pass = 0; pass < 2; pass++)
    {
        q.nonlinear = (pass == 1) && p->nonlinear;
        if (pass == 1 && !p->nonlinear)
        {
            *exn = *ex;
            break;
        }
        v34_enc_init(e, &q, 18);
        v34_enc_set_energy(e, *ex);
        prng_state = 0x12345678u;
        sum = 0.0;
        for (int i = 0; i < frames; i++)
        {
            v34_cf_t s[8];

            v34_enc_frame(e, prng_bit, NULL, prng_bit, NULL, s);
            for (int k = 0; k < 8; k++)
                sum += crealf(s[k]) * crealf(s[k]) + cimagf(s[k]) * cimagf(s[k]);
        }
        if (pass == 0)
            *ex = sum / (8.0 * frames);
        else
            *exn = sum / (8.0 * frames);
    }
    pthread_mutex_unlock(&lock);
    free(e);
}

/* -------------------------------------------------------------- decoder */

/* The two (s(2m), s(2m+1)) pairs that share Y4 Y3 Y2 Y1 and U0:
 * [U0][Y4 Y3 Y2 Y1][2]. */
static uint8_t branch_pairs[2][16][2];
static pthread_once_t branch_once = PTHREAD_ONCE_INIT;

static void build_branch_pairs(void)
{
    int n[2][16] = { { 0 } };

    for (int s0 = 0; s0 < 8; s0++)
        for (int s1 = 0; s1 < 8; s1++)
        {
            /* The low label bits count clockwise quarter turns, so U0 is the
             * parity of the difference between the two symbols' rotations,
             * Z + 2 I1 + U0 against Z. */
            int u0 = (s0 ^ s1) & 1;
            int yy = TABLE13[s0][s1];

            branch_pairs[u0][yy][n[u0][yy]++] = (uint8_t) ((s0 << 3) | s1);
        }
}

void v34_dec_init(v34_dec_t *d, const v34_data_params_t *p, int dscr_tap, v34_put_bit_t put_bit, void *user)
{
    tables();
    pthread_once(&branch_once, build_branch_pairs);
    memset(d, 0, sizeof(*d));
    d->p = *p;
    v34_frame_params(p, &d->f);
    v34_shell_init(&d->shell, d->f.M);
    d->dscr_tap = dscr_tap;
    d->put_bit = put_bit;
    d->user = user;
    d->states = (p->trellis == 32 || p->trellis == 64) ? p->trellis : 16;
    for (int s = 0; s < 64; s++)
        d->pm[s] = 1e9f;
    /* The encoder starts at zero (10.1.3.1). */
    d->pm[0] = 0.0f;
    d->err = 0.0f;
}

/* The nearest point of subset s to y, on the unbounded grid: in the a, b
 * coordinates of v34_subset_label the subset is a translate of 4Z x 4Z. */
static void nearest_in_subset(v34_cf_t y, int s, int *px, int *py)
{
    float a = 0.5f * (crealf(y) + cimagf(y));
    float b = 0.5f * (crealf(y) - cimagf(y));
    int a0 = label_ab[s][0], b0 = label_ab[s][1];
    int ai = a0 + 4 * (int) lrintf((a - (float) a0) / 4.0f);
    int bi = b0 + 4 * (int) lrintf((b - (float) b0) / 4.0f);

    *px = ai + bi;
    *py = ai - bi;
}

/* Which label of the quarter superconstellation, after undoing quads
 * clockwise turns; -1 if none. */
static int quarter_label(int x, int y, int quads)
{
    int vx, vy;

    rot_cw(x, y, (4 - (quads & 3)) & 3, &vx, &vy);
    if (vx <= -IDX_SPAN || vx >= IDX_SPAN || vy <= -IDX_SPAN || vy >= IDX_SPAN)
        return -1;
    return quarter_index[vx + IDX_SPAN][vy + IDX_SPAN];
}

/* A decision outside the constellation - noise near its edge - is moved to
 * the nearest point of the same subset that is in it, so that the subset,
 * which the trellis decided, is kept. */
static int clamp_point(const v34_dec_t *d, v34_cf_t y, int s, int *px, int *py)
{
    int lim = d->f.L / 4;
    int idx = quarter_label(*px, *py, s & 3);
    float best = 1e30f;

    if (idx >= 0 && idx < lim)
        return idx;
    for (int i = 0; i < lim; i++)
    {
        int x, yy;
        float dx, dy;

        rot_cw(v34_super[i][0], v34_super[i][1], s & 3, &x, &yy);
        if (v34_subset_label(x, yy) != s)
            continue;
        dx = crealf(y) - (float) x;
        dy = cimagf(y) - (float) yy;
        if (dx * dx + dy * dy < best)
        {
            best = dx * dx + dy * dy;
            *px = x;
            *py = yy;
            idx = i;
        }
    }
    return idx;
}

v34_cf_t v34_dec_slice(const v34_dec_t *d, v34_cf_t y)
{
    int x = 2 * (int) floorf(crealf(y) * 0.5f) + 1;
    int yy = 2 * (int) floorf(cimagf(y) * 0.5f) + 1;
    int s = v34_subset_label(x, yy);

    clamp_point(d, y, s, &x, &yy);
    return (float) x + I * (float) yy;
}

static void deliver(v34_dec_t *d, int bit)
{
    int b = v34_descramble(&d->dscr, d->dscr_tap, bit);

    if (d->deliver && d->put_bit != NULL)
        d->put_bit(d->user, b);
}

/* A whole mapping frame has been decided: put its bits back in the order the
 * parser took them (9.3). */
static void frame_out(v34_dec_t *d, long long i)
{
    const v34_frame_t *f = &d->f;
    bool high = frame_is_high(f, i);
    bool aux = frame_has_aux(f, i);
    uint32_t r0 = 0;
    int kk = 0;
    int with_i3;

    /* Everything after B1 is data; B1 itself is only there to be heard. */
    d->deliver = (i >= f->P);
    if (f->K > 0)
    {
        kk = high ? f->K : f->K - 1;
        if (!v34_shell_unmap(&d->shell, d->ring, f->K, &r0) || (!high && (r0 >> (f->K - 1)) != 0))
        {
            d->bad_frames++;
            r0 &= (1u << kk) - 1;
        }
        for (int k = 0; k < kk; k++)
            deliver(d, (int) ((r0 >> k) & 1));
        with_i3 = 4;
    }
    else
    {
        with_i3 = (high ? f->b : f->b - 1) - 8;
    }
    for (int j = 0; j < 4; j++)
    {
        int i1 = d->ibits[j] & 1;
        int i2 = (d->ibits[j] >> 1) & 1;
        int i3 = (d->ibits[j] >> 2) & 1;

        if (!(j == 0 && aux))
            deliver(d, i1);
        deliver(d, i2);
        if (j < with_i3)
            deliver(d, i3);
        for (int k = 0; k < 2; k++)
            for (int t = 0; t < f->q; t++)
                deliver(d, (d->qbits[2 * j + k] >> t) & 1);
    }
}

/* One decided 4D symbol, m_out, from the oldest end of the decoder. */
static void demap_4d(v34_dec_t *d, v34_cf_t y0, v34_cf_t y1, int pair)
{
    int s0 = pair >> 3, s1 = pair & 7;
    int x0, yy0, x1, yy1;
    int i0, i1;
    int r0 = s0 & 3, r1 = s1 & 3;
    int u0 = (r1 - r0) & 1;
    int j = (int) (d->m_out & 3);
    int ii;
    float e;

    nearest_in_subset(y0, s0, &x0, &yy0);
    nearest_in_subset(y1, s1, &x1, &yy1);
    i0 = clamp_point(d, y0, s0, &x0, &yy0);
    i1 = clamp_point(d, y1, s1, &x1, &yy1);
    e = (crealf(y0) - x0) * (crealf(y0) - x0) + (cimagf(y0) - yy0) * (cimagf(y0) - yy0) +
        (crealf(y1) - x1) * (crealf(y1) - x1) + (cimagf(y1) - yy1) * (cimagf(y1) - yy1);
    d->err += 0.002f * (0.5f * e - d->err);

    /* Z(m) is the first symbol's rotation, and the second's is Z + 2 I1 + U0. */
    ii = (r0 - d->zprev) & 3;
    d->zprev = r0;
    d->ibits[j] = (((r1 - r0 - u0) >> 1) & 1) | ((ii & 1) << 1) | ((ii >> 1) << 2);
    if (i0 < 0)
        i0 = 0;
    if (i1 < 0)
        i1 = 0;
    d->qbits[2 * j] = i0 & ((1 << d->f.q) - 1);
    d->ring[2 * j] = i0 >> d->f.q;
    d->qbits[2 * j + 1] = i1 & ((1 << d->f.q) - 1);
    d->ring[2 * j + 1] = i1 >> d->f.q;
    if (j == 3)
        frame_out(d, d->m_out / 4);
    d->m_out++;
}

static void subset_metrics(v34_cf_t y, float out[8])
{
    for (int s = 0; s < 8; s++)
    {
        int x, yy;
        float dx, dy;

        nearest_in_subset(y, s, &x, &yy);
        dx = crealf(y) - (float) x;
        dy = cimagf(y) - (float) yy;
        out[s] = dx * dx + dy * dy;
    }
}

void v34_dec_symbol(v34_dec_t *d, v34_cf_t y)
{
    const int ns_count = d->states;
    float m0[8], m1[8];
    float bm[2][16];
    uint8_t bp[2][16];
    float npm[64];
    uint8_t np[64], npair[64];
    int v0;
    int best = 0;
    float lo = 1e30f;

    if (!d->have_half)
    {
        d->half = y;
        d->have_half = true;
        return;
    }
    d->have_half = false;
    subset_metrics(d->half, m0);
    subset_metrics(y, m1);
    for (int u = 0; u < 2; u++)
        for (int k = 0; k < 16; k++)
        {
            int a = branch_pairs[u][k][0], b = branch_pairs[u][k][1];
            float va = m0[a >> 3] + m1[a & 7], vb = m0[b >> 3] + m1[b & 7];

            bm[u][k] = (va <= vb) ? va : vb;
            bp[u][k] = (uint8_t) ((va <= vb) ? a : b);
        }
    /* No precoding, so C0 is zero and U0 = Y0 ^ V0. */
    v0 = v34_v0(&d->f, d->m_in);
    for (int s = 0; s < ns_count; s++)
        npm[s] = 1e30f;
    for (int ps = 0; ps < ns_count; ps++)
    {
        int u = (ps & 1) ^ v0;

        for (int k = 0; k < 16; k++)
        {
            int nx = (ns_count == 64) ? conv64[ps][k] : (ns_count == 32) ? conv32[ps][k] : conv16[ps][k];
            float v = d->pm[ps] + bm[u][k];

            if (v < npm[nx])
            {
                npm[nx] = v;
                np[nx] = (uint8_t) ps;
                npair[nx] = bp[u][k];
            }
        }
    }
    for (int s = 0; s < ns_count; s++)
        if (npm[s] < lo)
        {
            lo = npm[s];
            best = s;
        }
    for (int s = 0; s < ns_count; s++)
    {
        d->pm[s] = npm[s] - lo;
        d->prev[d->vpos][s] = np[s];
        d->pair[d->vpos][s] = npair[s];
    }
    d->rx[d->vpos][0] = d->half;
    d->rx[d->vpos][1] = y;
    d->vpos = (d->vpos + 1) % V34_VIT_DEPTH;
    d->m_in++;
    if (d->m_in < V34_VIT_DEPTH)
        return;

    /* Trace back to the oldest 4D symbol held; it leaves the decoder. */
    {
        int s = best;
        int pos = (d->vpos - 1 + V34_VIT_DEPTH) % V34_VIT_DEPTH;

        for (int k = 0; k < V34_VIT_DEPTH - 1; k++)
        {
            s = d->prev[pos][s];
            pos = (pos - 1 + V34_VIT_DEPTH) % V34_VIT_DEPTH;
        }
        demap_4d(d, d->rx[pos][0], d->rx[pos][1], d->pair[pos][s]);
    }
}
